env:
  browser: true
  jquery: true
extends: 'eslint:recommended'
globals:
  google: false
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
