language: ruby
sudo: true
rvm:
  - 2.4.1

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - sudo apt-get install libcurl3-dev
  - gem install bundler:1.17.2

before_script: bundle exec jekyll build

script: travis_retry bundle exec htmlproofer --url-ignore "/www.tomesh.net/,/tomesh.net/" ./_site --allow-hash-href

notifications:
  email: false
